version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: InsuranceClaims
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insurance_claims
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=insurance_claims
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=InsuranceClaimsAPI.settings
    ports:
      - "8000:8000"
    volumes:
      - .:/app                              # Project code
      - static_volume:/app/staticfiles     # For collectstatic
    env_file:
      - .env
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py setup_initial_roles &&
      python manage.py sync_roles_and_groups &&
      python manage.py collectstatic --noinput &&
      gunicorn InsuranceClaimsAPI.wsgi:application --bind 0.0.0.0:8000
      "

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
