version: "3"

services:
  db:
    image: postgres:16-alpine
    container_name: InsuranceClaims
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insurance_claims
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=insurance_claims
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput && gunicorn InsuranceClaimsAPI.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
    driver: local
