services:
  postgreSQL:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    env_file:
      - .env  # ✅ Load database credentials from .env file
    environment:
      POSTGRES_DB: Student_Management
      POSTGRES_USER: postgreSQL
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    container_name: django_container
    restart: always
    depends_on:
      - postgreSQL
    env_file:
      - .env  # ✅ Load database credentials from .env file
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: