version: "3"

services:
  db:
    image: postgres:16-alpine
    container_name: InsuranceClaims  # Give PostgreSQL a distinct name
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insurance_claims
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 InsuranceClaims.wsgi:application"

volumes:
  postgres_data:
    driver: local
