# Generated by Django 5.1.6 on 2025-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False)),
                ('submittedBy', models.CharField(blank=True, max_length=150, null=True)),
                ('recordType', models.CharField(blank=True, max_length=150, null=True)),
                ('accidentDate', models.DateField(blank=True, null=True)),
                ('claimDate', models.DateField(blank=True, null=True)),
                ('settlementValue', models.FloatField(blank=True, null=True)),
                ('accidentType', models.CharField(blank=True, max_length=150, null=True)),
                ('injury_Prognosis', models.CharField(blank=True, max_length=150, null=True)),
                ('specialHealthExpenses', models.FloatField(blank=True, null=True)),
                ('specialReduction', models.FloatField(blank=True, null=True)),
                ('specialOverage', models.FloatField(blank=True, null=True)),
                ('generalRest', models.FloatField(blank=True, null=True)),
                ('specialAdditionalInjury', models.FloatField(blank=True, null=True)),
                ('specialEarningsLoss', models.FloatField(blank=True, null=True)),
                ('specialUsageLoss', models.FloatField(blank=True, null=True)),
                ('specialMedications', models.FloatField(blank=True, null=True)),
                ('specialAssetDamage', models.FloatField(blank=True, null=True)),
                ('specialRehabilitation', models.FloatField(blank=True, null=True)),
                ('specialFixes', models.FloatField(blank=True, null=True)),
                ('generalFixed', models.FloatField(blank=True, null=True)),
                ('generalUplift', models.FloatField(blank=True, null=True)),
                ('specialLoanerVehicle', models.FloatField(blank=True, null=True)),
                ('specialTripCosts', models.FloatField(blank=True, null=True)),
                ('specialJourneyExpenses', models.CharField(blank=True, max_length=150, null=True)),
                ('specialTherapy', models.CharField(blank=True, max_length=150, null=True)),
                ('exceptional_Circumstances', models.BooleanField(default=False)),
                ('minor_Psychological_Injury', models.BooleanField(default=False)),
                ('dominantInjury', models.CharField(blank=True, max_length=150, null=True)),
                ('whiplash', models.BooleanField(default=False)),
                ('vehicleType', models.CharField(blank=True, max_length=150, null=True)),
                ('weatherConditions', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicleAge', models.IntegerField(blank=True, null=True)),
                ('driverAge', models.IntegerField(blank=True, null=True)),
                ('numberOfPassengers', models.IntegerField(blank=True, null=True)),
                ('accidentDescription', models.TextField(blank=True, null=True)),
                ('injuryDescription', models.TextField(blank=True, null=True)),
                ('policeReportFiled', models.BooleanField(default=False)),
                ('witnessPresent', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('lastModifiedDate', models.DateField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
