# Generated by Django 5.0.2 on 2025-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(blank=True, max_length=150, null=True)),
                ('settlement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accident_type', models.CharField(blank=True, max_length=150, null=True)),
                ('injury_prognosis', models.CharField(blank=True, max_length=150, null=True)),
                ('special_health_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_overage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('general_rest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_additional_injury', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_earnings_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_usage_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_medications', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_asset_damage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_rehabilitation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_fixes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('general_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('general_uplift', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_loaner_vehicle', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_trip_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_journey_expenses', models.CharField(blank=True, max_length=150, null=True)),
                ('special_therapy', models.CharField(blank=True, max_length=150, null=True)),
                ('exceptional_circumstances', models.BooleanField(default=False)),
                ('minor_psychological_injury', models.BooleanField(default=False)),
                ('dominant_injury', models.CharField(blank=True, max_length=150, null=True)),
                ('whiplash', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=150, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_age', models.IntegerField(blank=True, null=True)),
                ('driver_age', models.IntegerField(blank=True, null=True)),
                ('number_of_passengers', models.IntegerField(blank=True, null=True)),
                ('accident_description', models.TextField(blank=True, null=True)),
                ('injury_description', models.TextField(blank=True, null=True)),
                ('police_report_filed', models.BooleanField(default=False)),
                ('witness_present', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('accident_date', models.DateField(blank=True, null=True)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='InsuranceCl_status_a3e857_idx'), models.Index(fields=['accident_date'], name='InsuranceCl_acciden_ac6feb_idx')],
            },
        ),
    ]
