# Generated by Django 5.1.6 on 2025-03-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsRecords', '0003_record_delete_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='specialReduction',
            new_name='specialReductions',
        ),
    ]
