# Generated by Django 5.1.6 on 2025-03-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsRecords', '0004_rename_specialreduction_record_specialreductions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='specialReductions',
            new_name='specialReduction',
        ),
    ]
