# Generated by Django 5.1.6 on 2025-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsRecords', '0005_rename_specialreductions_record_specialreduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='accidentDate',
            new_name='accident_date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='accidentDescription',
            new_name='accident_description',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='accidentType',
            new_name='accident_type',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='claimDate',
            new_name='claim_date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='dominantInjury',
            new_name='dominant_injury',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='driverAge',
            new_name='driver_age',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='injuryDescription',
            new_name='injury_description',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='injury_Prognosis',
            new_name='injury_prognosis',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='exceptional_Circumstances',
            new_name='is_exceptional_circumstances',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='minor_Psychological_Injury',
            new_name='is_minor_psychological_injury',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='policeReportFiled',
            new_name='is_police_report_filed',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='whiplash',
            new_name='is_whiplash',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='witnessPresent',
            new_name='is_witness_present',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='lastModifiedDate',
            new_name='last_modified_date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='numberOfPassengers',
            new_name='number_of_passengers',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recordId',
            new_name='record_id',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recordType',
            new_name='record_type',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='specialJourneyExpenses',
            new_name='special_journey_expenses',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='specialTherapy',
            new_name='special_therapy',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='submittedBy',
            new_name='submitted_by',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='vehicleAge',
            new_name='vehicle_age',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='vehicleType',
            new_name='vehicle_type',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='weatherConditions',
            new_name='weather_conditions',
        ),
        migrations.RemoveField(
            model_name='record',
            name='generalFixed',
        ),
        migrations.RemoveField(
            model_name='record',
            name='generalRest',
        ),
        migrations.RemoveField(
            model_name='record',
            name='generalUplift',
        ),
        migrations.RemoveField(
            model_name='record',
            name='settlementValue',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialAdditionalInjury',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialAssetDamage',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialEarningsLoss',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialFixes',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialHealthExpenses',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialLoanerVehicle',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialMedications',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialOverage',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialReduction',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialRehabilitation',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialTripCosts',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specialUsageLoss',
        ),
        migrations.AddField(
            model_name='record',
            name='general_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='general_rest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='general_uplift',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='settlement_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_additional_injury',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_asset_damage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_earnings_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_fixes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_health_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_loaner_vehicle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_medications',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_overage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_rehabilitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_trip_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='special_usage_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['status'], name='InsuranceCl_status_a3e857_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['accident_date'], name='InsuranceCl_acciden_ac6feb_idx'),
        ),
    ]
