# Generated by Django 5.1.6 on 2025-03-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsRecords', '0006_rename_accidentdate_record_accident_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='is_exceptional_circumstances',
            new_name='exceptional_circumstances',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='is_minor_psychological_injury',
            new_name='minor_psychological_injury',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='is_police_report_filed',
            new_name='police_report_filed',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='is_whiplash',
            new_name='whiplash',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='is_witness_present',
            new_name='witness_present',
        ),
    ]
