# Generated by Django 5.1.6 on 2025-03-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsRecords', '0007_rename_is_exceptional_circumstances_record_exceptional_circumstances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='submitted_by',
        ),
    ]
