# Generated by Django 5.0.2 on 2025-04-28 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_type', models.CharField(max_length=100)),
                ('injury_prognosis', models.CharField(max_length=100)),
                ('settlement_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccidentType', models.CharField(max_length=100)),
                ('Injury_Prognosis', models.CharField(max_length=100)),
                ('Exceptional_Circumstances', models.CharField(max_length=3)),
                ('Minor_Psychological_Injury', models.CharField(max_length=3)),
                ('Dominant_injury', models.CharField(max_length=100)),
                ('Whiplash', models.CharField(max_length=3)),
                ('Vehicle_Type', models.CharField(max_length=100)),
                ('Weather_Conditions', models.CharField(max_length=100)),
                ('Accident_Description', models.TextField()),
                ('Injury_Description', models.TextField()),
                ('Police_Report_Filed', models.CharField(max_length=3)),
                ('Witness_Present', models.CharField(max_length=3)),
                ('Gender', models.CharField(max_length=10)),
                ('Driver_Age', models.IntegerField()),
                ('Vehicle_Age', models.IntegerField()),
                ('Number_of_Passengers', models.IntegerField()),
                ('SpecialHealthExpenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialReduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialOverage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GeneralRest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialAdditionalInjury', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialEarningsLoss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialUsageLoss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialMedications', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialAssetDamage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialRehabilitation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialFixes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GeneralFixed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GeneralUplift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialLoanerVehicle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialTripCosts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialJourneyExpenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SpecialTherapy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Accident_Date', models.DateField()),
                ('Claim_Date', models.DateField()),
                ('predicted_settlement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
