# Generated by Django 5.1.6 on 2025-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury', models.CharField(choices=[('minor', 'Minor Injury'), ('moderate', 'Moderate Injury'), ('severe', 'Severe Injury')], max_length=50)),
                ('earnings', models.CharField(choices=[('low', 'Less than $1,000'), ('medium', '$1,000 - $5,000'), ('high', 'More than $5,000')], max_length=50)),
                ('expenses', models.CharField(choices=[('none', 'None'), ('medical', 'Medical Costs'), ('legal', 'Legal Fees')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
