# Generated by Django 5.1.6 on 2025-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsCustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettlementValue', models.FloatField(blank=True, null=True)),
                ('AccidentType', models.CharField(blank=True, max_length=255, null=True)),
                ('Injury_Prognosis', models.CharField(blank=True, max_length=255, null=True)),
                ('SpecialHealthExpenses', models.FloatField(blank=True, null=True)),
                ('SpecialReduction', models.FloatField(blank=True, null=True)),
                ('SpecialOverage', models.FloatField(blank=True, null=True)),
                ('GeneralRest', models.FloatField(blank=True, null=True)),
                ('SpecialAdditionalInjury', models.FloatField(blank=True, null=True)),
                ('SpecialEarningsLoss', models.FloatField(blank=True, null=True)),
                ('SpecialUsageLoss', models.FloatField(blank=True, null=True)),
                ('SpecialMedications', models.FloatField(blank=True, null=True)),
                ('SpecialAssetDamage', models.FloatField(blank=True, null=True)),
                ('SpecialRehabilitation', models.FloatField(blank=True, null=True)),
                ('SpecialFixes', models.FloatField(blank=True, null=True)),
                ('GeneralFixed', models.FloatField(blank=True, null=True)),
                ('GeneralUplift', models.FloatField(blank=True, null=True)),
                ('SpecialLoanerVehicle', models.FloatField(blank=True, null=True)),
                ('SpecialTripCosts', models.FloatField(blank=True, null=True)),
                ('SpecialJourneyExpenses', models.FloatField(blank=True, null=True)),
                ('SpecialTherapy', models.FloatField(blank=True, null=True)),
                ('Exceptional_Circumstances', models.CharField(blank=True, max_length=255, null=True)),
                ('Minor_Psychological_Injury', models.CharField(blank=True, max_length=255, null=True)),
                ('Dominant_injury', models.CharField(blank=True, max_length=255, null=True)),
                ('Whiplash', models.CharField(blank=True, max_length=255, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Weather_Conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('Accident_Date', models.DateTimeField(blank=True, null=True)),
                ('Claim_Date', models.DateTimeField(blank=True, null=True)),
                ('Vehicle_Age', models.FloatField(blank=True, null=True)),
                ('Driver_Age', models.FloatField(blank=True, null=True)),
                ('Number_of_Passengers', models.FloatField(blank=True, null=True)),
                ('Accident_Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Injury_Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Police_Report_Filed', models.CharField(blank=True, max_length=255, null=True)),
                ('Witness_Present', models.CharField(blank=True, max_length=255, null=True)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
