# Generated by Django 5.0.2 on 2025-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsCustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclaim',
            name='temp_field',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
