# Generated by Django 5.1.6 on 2025-04-20 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsCustomer', '0002_insuranceclaim_delete_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccidentType', models.CharField(max_length=100)),
                ('Injury_Prognosis', models.CharField(max_length=100)),
                ('SpecialHealthExpenses', models.FloatField()),
                ('SpecialReduction', models.FloatField()),
                ('SpecialOverage', models.FloatField()),
                ('GeneralRest', models.FloatField()),
                ('SpecialAdditionalInjury', models.FloatField()),
                ('SpecialEarningsLoss', models.FloatField()),
                ('SpecialUsageLoss', models.FloatField()),
                ('SpecialMedications', models.FloatField()),
                ('SpecialAssetDamage', models.FloatField()),
                ('SpecialRehabilitation', models.FloatField()),
                ('SpecialFixes', models.FloatField()),
                ('GeneralFixed', models.FloatField()),
                ('GeneralUplift', models.FloatField()),
                ('SpecialLoanerVehicle', models.FloatField()),
                ('SpecialTripCosts', models.FloatField()),
                ('SpecialJourneyExpenses', models.FloatField()),
                ('SpecialTherapy', models.FloatField()),
                ('Exceptional_Circumstances', models.CharField(max_length=100)),
                ('Minor_Psychological_Injury', models.CharField(max_length=100)),
                ('Dominant_injury', models.CharField(max_length=100)),
                ('Whiplash', models.CharField(max_length=100)),
                ('Vehicle_Type', models.CharField(max_length=100)),
                ('Weather_Conditions', models.CharField(max_length=100)),
                ('Accident_Date', models.DateField()),
                ('Claim_Date', models.DateField()),
                ('Vehicle_Age', models.IntegerField()),
                ('Driver_Age', models.IntegerField()),
                ('Number_of_Passengers', models.IntegerField()),
                ('Accident_Description', models.TextField()),
                ('Injury_Description', models.TextField()),
                ('Police_Report_Filed', models.CharField(max_length=3)),
                ('Witness_Present', models.CharField(max_length=3)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='AccidentType',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Accident_Date',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Accident_Description',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Claim_Date',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Dominant_injury',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Driver_Age',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Exceptional_Circumstances',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='GeneralFixed',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='GeneralRest',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='GeneralUplift',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Injury_Description',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Injury_Prognosis',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Minor_Psychological_Injury',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Number_of_Passengers',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Police_Report_Filed',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SettlementValue',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialAdditionalInjury',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialAssetDamage',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialEarningsLoss',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialFixes',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialHealthExpenses',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialJourneyExpenses',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialLoanerVehicle',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialMedications',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialOverage',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialReduction',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialRehabilitation',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialTherapy',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialTripCosts',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='SpecialUsageLoss',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Vehicle_Age',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Vehicle_Type',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Weather_Conditions',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Whiplash',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='Witness_Present',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='accident_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='settlement_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='injury_prognosis',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
