# Generated by Django 5.1.6 on 2025-05-08 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsCustomer', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='customer_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='InsuranceClaimsCustomer.customerclaim'),
        ),
    ]
