# Generated by Django 5.1.6 on 2025-03-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsUser', '0002_roles_and_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'name')},
        ),
    ]
