# Generated by Django 5.0.2 on 2025-03-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsUser', '0002_add_finance_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'name')},
        ),
    ]
