# Generated by Django 5.0.2 on 2025-04-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceClaimsUser', '0002_roles_and_permissions'),
        ('InsuranceClaimsUser', '0004_merge_ai_engineer_and_permission_changes'),
    ]

    operations = [
    ]
